openapi: 3.0.0
info:
  title: ankuzo-yandex-playlist-resolver
  version: 1.0.0

x-yc-apigateway:
  cors:
    origin: "*"
    methods:
      - GET
      - OPTIONS
    allowedHeaders: "*"

paths:
  /playlist/{uuid}:
    get:
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            pattern: "^[a-fA-F0-9-]{36}$"
      responses:
        "200":
          description: Yandex Music playlist metadata
      x-yc-apigateway-integration:
        type: http
        method: GET
        url: https://api.music.yandex.net/playlist/{uuid}
        timeouts:
          connect: 2
          read: 10
